# Generated by Django 6.0.3 on 2026-05-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='endpoint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
